### ISSUE TITLE
Add GCP library used for terraform policies

### ISSUE THREAD

**Issue by jralmaraz** [anderseknert/awesome-opa#28]
Since reading this recent blog post https://cloud.google.com/blog/products/compliance/google-cloud-cli-terraform-validation-preview I wanted to know if you have been working on GCP related policies and if you would consider adding to the awesome-opa too :)

They seem to be keeping the policies here:

https://github.com/GoogleCloudPlatform/policy-library/tree/main/validator

Cheers!

**Comment by anderseknert** [comment]
Of course! Would you consider submitting a PR for that? :)

**Comment by jralmaraz** [comment]
Definitely, just thought of checking if you think its a meaningful content :)

**Comment by jralmaraz** [comment]
Let me know if this one is ok @anderseknert , cheers!
