### ISSUE TITLE
Category for WebAssembly-compiled OPA policies?

### ISSUE THREAD

**Issue by christophwille** [anderseknert/awesome-opa#4]
Neither the official npm nor the Go SDK are listed yet - so, where should https://github.com/christophwille/csharp-opa-wasm go? (I think it should be grouped around wasm and not added to the language listings)

**Comment by anderseknert** [comment]
Agreed, I think WASM deserve a category of its own. A new top level section after "Language integrations" with yours and the Go / Node ones, WDYT?

**Comment by christophwille** [comment]
That location sounds about right. Have sub-sections for "SDKs", "Docs" and "Blogs and articles".

**Comment by anderseknert** [comment]
Sounds great! Will you do the honors?

**Comment by christophwille** [comment]
Can do, but... maybe you know more links than I do? (most of the things I used I put on the root README on my repo)

**Comment by anderseknert** [comment]
Give it a shot and I can add more later. Not trying to be lazy about it, more like I'd appreciate seeing some contributors listed for the project rather than looking like a one man show, which it certainly isn't given a lot of links are from the OPA Slack, and so on :)
